# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(670, 591)
        self.pushButton_noise = QtWidgets.QPushButton(Form)
        self.pushButton_noise.setGeometry(QtCore.QRect(240, 70, 141, 71))
        self.pushButton_noise.setObjectName("pushButton_noise")
        self.pushButton_detect = QtWidgets.QPushButton(Form)
        self.pushButton_detect.setGeometry(QtCore.QRect(240, 230, 141, 61))
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.pushButton_recognition = QtWidgets.QPushButton(Form)
        self.pushButton_recognition.setGeometry(QtCore.QRect(240, 300, 141, 61))
        self.pushButton_recognition.setObjectName("pushButton_recognition")
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(240, 370, 141, 61))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 30, 641, 471))
        self.widget.setObjectName("widget")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.widget)
        self.openGLWidget.setGeometry(QtCore.QRect(210, 20, 300, 411))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton_edge = QtWidgets.QPushButton(Form)
        self.pushButton_edge.setGeometry(QtCore.QRect(240, 150, 141, 71))
        self.pushButton_edge.setObjectName("pushButton_edge")
        self.pushButton_edge.raise_()
        self.pushButton_noise.raise_()
        self.pushButton_detect.raise_()
        self.pushButton_recognition.raise_()
        self.pushButton_exit.raise_()
        self.widget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton_noise, self.pushButton_detect)
        Form.setTabOrder(self.pushButton_detect, self.pushButton_recognition)
        Form.setTabOrder(self.pushButton_recognition, self.pushButton_exit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_noise.setText(_translate("Form", "loai bo noise"))
        self.pushButton_detect.setText(_translate("Form", "face detect "))
        self.pushButton_recognition.setText(_translate("Form", "face recognition"))
        self.pushButton_exit.setText(_translate("Form", "thoat"))
        self.pushButton_edge.setText(_translate("Form", "Edge Detection"))
